// Demo-only compact synchronization; raw child events never pass through this relay.
export const commands = ['ENTER_CHILD_MODE', 'EXIT_CHILD_MODE', 'START_SESSION', 'PAUSE_SESSION', 'RESUME_SESSION', 'NEXT_ACTIVITY', 'END_SESSION'];
export interface Slot {category: string; minutes: number; mode: string; gameType: string;}
export interface Command {id: string; type: string; minutes: number; slots: Slot[]; difficulty: number;}
export interface Status {active: boolean; paused: boolean; ended: boolean; sessionId: string; world: string; mission: string; style: string; phase: string; remaining: number; completed: number; total: number;}
export interface Result {id: string; sessionId: string; activityId: string; title: string; style: string; category: string; completed: boolean; skipped: boolean; attempts: number; retries: number; duration: number; timestamp: number; feedback: string; difficultyFeedback: string; movementConfirmed: boolean;}
const styles = ['BUILDING','MEMORY','SORTING','COUNTING','EXPLORING','CREATING','MOVEMENT','WATCHING'];
const text = (v: unknown, max = 100) => typeof v === 'string' && v.length <= max;
const integer = (v: unknown, max = 1000000) => typeof v === 'number' && Number.isInteger(v) && v >= 0 && v <= max;
export function validResult(r: Result): boolean {return !!r && text(r.id) && text(r.sessionId) && text(r.activityId, 40) && text(r.title) && styles.includes(r.style) && ['MOVE','LEARN','CREATE','CALM'].includes(r.category) && [r.completed,r.skipped,r.movementConfirmed].every(v=>typeof v==='boolean') && r.completed !== r.skipped && [r.attempts,r.retries,r.duration].every(v=>integer(v)) && integer(r.timestamp, Number.MAX_SAFE_INTEGER) && ['','liked','okay','disliked'].includes(r.feedback) && ['','too easy','just right','too hard'].includes(r.difficultyFeedback);}
export function validStatus(s: Status): boolean { return !!s && [s.active,s.paused,s.ended].every(v=>typeof v==='boolean') && [s.sessionId,s.world,s.mission].every(v=>text(v)) && styles.includes(s.style) && ['hub','input','preview','retry','movement','confirm','success','feedback','ending','watch'].includes(s.phase) && integer(s.remaining,3600) && integer(s.completed,300) && integer(s.total,20); }
export class WorldRelay {
  private rooms = new Map<string, {commands: Command[]; status?: Status; results: Result[]; phoneAt: number; tabletAt: number}>();
  private room(code: string) { if (!/^[a-zA-Z0-9_-]{4,32}$/.test(code)) throw Error('Invalid room'); if(!this.rooms.has(code)){if(this.rooms.size>=100)throw Error('Room limit');this.rooms.set(code,{commands:[],results:[],phoneAt:0,tabletAt:0});} return this.rooms.get(code)!; }
  command(code: string, c: Command, now=Date.now()) { if (!c || !text(c.id) || !c.id || !commands.includes(c.type) || ![15,30,45,60].includes(c.minutes) || !integer(c.difficulty,5) || c.difficulty<2 || !Array.isArray(c.slots) || c.slots.length>20 || c.slots.some(s=> !s || !['MOVE','LEARN','CREATE','CALM'].includes(s.category) || !integer(s.minutes,5) || s.minutes<1 || !['VIDEO','INTERACTIVE','GUIDED_OFFSCREEN'].includes(s.mode) || !text(s.gameType,40))) throw Error('Invalid world command');
    if(c.type==='START_SESSION' && (!c.slots.length || c.slots.reduce((a,s)=>a+s.minutes,0)!==c.minutes))throw Error('Invalid session allocation');
    const r=this.room(code);r.phoneAt=now;if(!r.commands.some(x=>x.id===c.id))r.commands=[...r.commands,c].slice(-50); }
  tablet(code: string, value: {status: Status; results: Result[]}, now=Date.now()) {if(!value || !validStatus(value.status) || !Array.isArray(value.results) || value.results.length>300 || value.results.some(r=>!validResult(r)))throw Error('Invalid compact summary');const room=this.room(code);room.status=value.status;room.tabletAt=now;const map=new Map(room.results.map(r=>[r.id,r]));for(const r of value.results){const old=map.get(r.id);if(!old || (old.sessionId===r.sessionId && old.activityId===r.activityId && old.completed===r.completed && old.skipped===r.skipped))map.set(r.id,r);}room.results=[...map.values()].slice(-300);}
  poll(code: string, role: string, now=Date.now()) {const r=this.room(code);if(role==='phone')r.phoneAt=now;return {commands:role==='tablet'?r.commands:[],status:r.status,results:role==='phone'?r.results:[],connected:(role==='phone'?r.tabletAt:r.phoneAt)>0 && now-(role==='phone'?r.tabletAt:r.phoneAt)<6000};}
}
