// Actual shared ArkTS rules, not screenshots or mocked game success.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const ts=require(path.resolve(process.argv[2]));const cache=new Map();
function load(file){file=path.resolve(__dirname,'..',file);if(cache.has(file))return cache.get(file);const box={exports:{},Date,Math,Number,JSON,Array,require:id=>id==='@companion/protocol'?require('./load-protocol.cjs')(ts):load(path.relative(path.resolve(__dirname,'..'),path.resolve(path.dirname(file),id+'.ets')))};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2021}}).outputText,box);cache.set(file,box.exports);return box.exports;}
const {GameEngine:E,validGame,gameDefinition,GAME_IDS}=load('shared/InteractiveActivity.ets');
const {JourneyState,parseJourney,claimActivity,completeAdventure,collectibles}=load('entry/src/main/ets/model/AdventureJourney.ets');
const {Completion,ParentSettings}=load('entry/src/main/ets/model/Companion.ets');const {planWork,settleEntry,parseWork}=load('entry/src/main/ets/model/WorkSession.ets');
let passed=0;function test(name,run){run();passed++;console.log('PASS '+name)}const at=100000;
function act(state,action,value='',time=at){return E.act(state,action,value,time)}
test('CHOICE requires three valid rounds, wrong answer blocks advancement, retry is explicit',()=>{let s=E.start(E.create('dino-number'),at);let r=act(s,'answer','2');assert.equal(r.state.phase,'retry');assert.ok(r.events.includes('ANSWER_INCORRECT'));s=act(r.state,'retry').state;assert.equal(s.retries,1);for(const value of ['3','5','4']){r=act(s,'answer',value);s=r.state;if(s.phase==='round-success')s=act(s,'next').state;}assert.equal(s.phase,'success');assert.equal(s.attempts,4);assert.equal(s.correct,3);assert.equal(act(s,'answer','4').events.length,0)});
test('MEMORY preview actually hides, order is entered item-by-item; incorrect order supports retry',()=>{for(const level of ['Gentle','Standard','Hard']){let s=E.start(E.create('robot-memory',level),at);assert.equal(s.phase,'preview');assert.equal(act(s,'answer','Star').events.length,0);s=E.tick(s,at+5000);assert.equal(s.phase,'input');for(let i=0;i<s.sequence.length;i++)s=act(s,'answer','Dino',at+5000).state;assert.equal(s.phase,'retry');s=act(s,'retry','',at+5000).state;s=E.tick(s,at+10000);for(const value of s.sequence)s=act(s,'answer',value,at+10000).state;assert.equal(s.phase,'success');assert.equal(s.attempts,2);assert.equal(s.retries,1);assert.equal(s.selected.join(','),s.sequence.join(','));}});
test('SORTING validates every destination and completes only after all three animals',()=>{let s=E.start(E.create('animal-sorting'),at);s=act(s,'answer','Land').state;assert.equal(s.phase,'retry');s=act(s,'retry').state;for(const value of ['Water','Land','Water']){s=act(s,'answer',value).state;if(s.phase==='round-success')s=act(s,'next').state;}assert.equal(s.phase,'success');assert.equal(s.correct,3);assert.equal(s.attempts,4)});
test('PENGUIN countdown gates Done, More Time starts real timer, Skip is recorded',()=>{let s=E.start(E.create('penguin-move'),at);assert.equal(act(s,'done').events.length,0);s=E.tick(s,at+10000);assert.equal(s.phase,'confirm');let r=act(s,'more','',at+10000);assert.ok(r.events.includes('NEED_MORE_TIME'));assert.equal(r.state.phase,'movement');s=E.tick(r.state,at+20000);r=act(s,'done','',at+20000);assert.equal(r.state.phase,'success');assert.equal(r.state.movementConfirmed,true);assert.ok(r.events.includes('MOVEMENT_CONFIRMED'));assert.ok(act(E.start(E.create('penguin-move'),at),'skip').events.includes('ACTIVITY_SKIPPED'))});
test('NUMBER MOVE requires learning success AND timed movement self-confirmation',()=>{let s=E.start(E.create('number-move'),at);s=act(s,'answer','2').state;assert.equal(s.phase,'retry');s=act(s,'retry').state;s=act(s,'answer','4').state;assert.equal(s.phase,'movement');assert.equal(s.learned,true);assert.equal(s.movementConfirmed,false);assert.equal(act(s,'done').events.length,0);s=E.tick(s,at+10000);s=act(s,'done','',at+10000).state;assert.equal(s.phase,'success');assert.equal(s.learned&&s.movementConfirmed,true)});
test('game snapshots survive serialization, pause/resume and reject malformed sequence/difficulty',()=>{let s=E.start(E.create('robot-memory'),at);s=E.pause(s,at+2000);assert.equal(E.tick(s,at+10000).phase,'preview');s=E.resume(s,at+10000);assert.equal(E.tick(s,at+13000).phase,'input');assert.equal(validGame(JSON.parse(JSON.stringify(s))),true);assert.equal(validGame({...s,selected:['secret']}),false);assert.equal(validGame({...s,difficulty:'clinical'}),false);for(const id of GAME_IDS)assert.equal(gameDefinition(id).safetyFlags.includes('NO_JUMPING'),true)});
test('Daily Adventure partial work and game checkpoint survive restart; finite completion never adds entries',()=>{let w=planWork(30,new ParentSettings());w.daily=true;w.adventureDate='2026-10-4';w.game=E.start(E.create('dino-number'),at);w=settleEntry(w,'completed',false);assert.equal(parseWork(JSON.stringify(w)).daily,true);const length=w.entries.length;while(w.phase==='active')w=settleEntry(w,'completed',false);assert.equal(w.phase,'completed');assert.equal(w.entries.length,length)});
test('mixed work plan preserves video and interactive learning with four protected categories',()=>{const w=planWork(30,new ParentSettings());assert.ok(w.entries.some(e=>e.mode==='INTERACTIVE'));assert.ok(w.entries.some(e=>e.mode==='VIDEO'));assert.ok(['MOVE','LEARN','CREATE','CALM'].every(c=>w.entries.some(e=>e.category===c)));assert.equal(w.entries.filter(e=>e.mode==='VIDEO').reduce((n,e)=>n+e.minutes,0),9)});
test('Journey counts and deterministic collectibles persist across missed days without resets or duplication',()=>{let j=new JourneyState();const now=new Date(2026,9,4).getTime();j=completeAdventure(j,'2026-10-4',false,now);j=completeAdventure(j,'2026-10-4',false,now);assert.equal(j.worlds[0],1);j=completeAdventure(j,'2026-10-15',false,now+11*86400000);assert.equal(j.completedDays.length,2);for(let i=0;i<3;i++){const r=new Completion();r.id='move-'+i;r.completed=true;r.movementConfirmed=true;j=claimActivity(j,r);j=claimActivity(j,r)}assert.equal(j.movement,3);assert.ok(collectibles(parseJourney(JSON.stringify(j))).some(t=>t.includes('Movement Explorer')));assert.equal(parseJourney('{bad').completedDays.length,0)});
test('Demo story progress is labelled separately and cannot grant normal collectibles',()=>{let j=completeAdventure(new JourneyState(),'2026-10-4',true,at);assert.equal(j.demoDays.length,1);assert.equal(j.completedDays.length,0);const r=new Completion();r.id='demo';r.demo=true;r.movementConfirmed=true;j=claimActivity(j,r);assert.equal(j.movement,0);assert.equal(collectibles(j).length,0)});
console.log(`${passed} actual mini-game and journey host checks passed`);
