const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const ts=require(path.resolve(process.argv[2]));const box={exports:{},Date,Math,Number,JSON,Array};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../shared/ChildWorldModel.ets'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2021}}).outputText,box);
const {WorldEngine:E,WorldState,WorldCommand,WorldSlot,parseWorld}=box.exports;
let passed=0;function test(name,run){run();passed++;console.log('PASS '+name)};const at=Date.now();
function open(game){const s=new WorldState();s.active=true;return E.open(s,game,at)}
function act(s,a,v=0,n=at){return E.act(s,a,v,n)}
test('Bridge has three actual placements; wrong placement returns to retry and duplicate stone never advances',()=>{let s=open('bridge');s=act(s,'place',-1);assert.equal(s.phase,'retry');s=act(s,'retry');s=act(s,'place',0);s=act(s,'place',0);assert.equal(s.progress,1);for(const i of [1,2])s=act(s,'place',i);assert.equal(s.phase,'success');s.feedback='liked';s=E.next(s,at);assert.equal(s.results.length,1);assert.equal(s.results[0].attempts,4);assert.equal(s.results[0].feedback,'liked');s=E.next(s,at);assert.equal(s.results.length,1)});
test('Memory flashes individual signals and locks all input; 2/3/4/5 signals validate in order after retry',()=>{for(const count of [2,3,4,5]){let s=new WorldState();s.active=true;s.difficulty=count;s=E.open(s,'memory',at);assert.equal(act(s,'panel',0).progress,0);s=E.tick(s,at+1000);assert.equal(s.flash,1);s=E.tick(s,at+(count+1)*1000);assert.equal(s.phase,'input');s=act(s,'panel',3);assert.equal(s.phase,'retry');s=act(s,'retry');s=E.tick(s,at+(count+1)*1000);for(const v of s.sequence)s=act(s,'panel',v);assert.equal(s.phase,'success');assert.equal(s.retries,1)}});
test('Animals require selecting actual animal and habitat; invalid placement cannot save completion',()=>{let s=open('rescue');s=act(s,'habitat',1);assert.equal(s.progress,0);s=act(s,'select',0);s=act(s,'habitat',0);assert.equal(s.phase,'retry');s=act(s,'retry');for(const [animal,home] of [[0,1],[1,0],[2,1]]){s=act(s,'select',animal);s=act(s,'habitat',home)}assert.equal(s.phase,'success');assert.equal(s.placed.length,3)});
test('Collect exactly five blue stars; amber handling and repeated taps are real validation',()=>{let s=open('stars');s=act(s,'collect',5);assert.equal(s.phase,'retry');s=act(s,'retry');for(let i=0;i<5;i++){s=act(s,'collect',i);s=act(s,'collect',i)}assert.equal(s.phase,'success');assert.equal(s.progress,5)});
test('Movement uses real ten-second foreground demonstration, More Time and child confirmation',()=>{let s=open('copy');assert.equal(act(s,'done').phase,'movement');s=E.tick(s,at+1000);assert.equal(s.remaining,9);s=act(s,'more',0,at+1000);assert.equal(s.remaining,10);for(let i=2;i<=11;i++)s=E.tick(s,at+i*1000);assert.equal(s.phase,'confirm');s=act(s,'done');s=E.next(s,at+11000);assert.equal(s.results[0].movementConfirmed,true)});
test('Number Move requires four physical crystals before movement, never a number answer button',()=>{let s=open('number');s=act(s,'collect',4);assert.equal(s.phase,'retry');s=act(s,'retry');for(let i=0;i<4;i++)s=act(s,'collect',i);assert.equal(s.phase,'movement');for(let i=1;i<=10;i++)s=E.tick(s,at+i*1000);s=act(s,'done');s=E.next(s,at+10000);assert.equal(s.results[0].completed,true)});
test('Rocket has three matching objects; creativity has no wrong answers; calm has no score',()=>{let s=open('rocket');for(let i=0;i<3;i++)s=act(s,'place',i);assert.equal(s.phase,'success');s=open('garden');s=act(s,'done');assert.equal(s.phase,'input');s=act(s,'flower',4);s=act(s,'done');assert.equal(s.phase,'success');assert.equal(s.attempts,0);s=open('calm');s=act(s,'cloud');s=act(s,'done');assert.equal(s.phase,'success');assert.equal(s.attempts,0)});
test('Remote mode/session controls acknowledged locally, command replay cannot restart or skip twice',()=>{let s=new WorldState();const c=new WorldCommand();c.id='enter';c.type='ENTER_CHILD_MODE';s=E.command(s,c,at);assert.equal(s.active,true);c.id='start';c.type='START_SESSION';c.minutes=15;c.slots=[new WorldSlot(),new WorldSlot()];s=E.command(s,c,at);const id=s.missionId;s=E.command(s,c,at+100);assert.equal(s.missionId,id);c.id='pause';c.type='PAUSE_SESSION';s=E.command(s,c,at);assert.equal(s.paused,true);const paused=E.tick(s,at+50000);assert.equal(paused.sessionRemaining,s.sessionRemaining);c.id='resume';c.type='RESUME_SESSION';s=E.command(paused,c,at+50000);assert.equal(s.paused,false);c.id='next';c.type='NEXT_ACTIVITY';s=E.command(s,c,at+50000);const count=s.results.length;s=E.command(s,c,at+51000);assert.equal(s.results.length,count);c.id='end';c.type='END_SESSION';s=E.command(s,c,at);assert.equal(s.phase,'ending');c.id='exit';c.type='EXIT_CHILD_MODE';s=E.command(s,c,at);assert.equal(s.active,false)});
test('Disconnect leaves local engine usable; restart preserves raw local events/results; malformed storage restores safely',()=>{let s=open('bridge');s=act(s,'place',0);let restored=parseWorld(JSON.stringify(s));assert.equal(restored.progress,1);for(const i of [1,2])restored=act(restored,'place',i);restored=E.next(restored,at);assert.equal(restored.results.length,1);assert.ok(restored.events.length>=4);assert.equal(parseWorld('{broken').phase,'hub');const corrupt=JSON.parse(JSON.stringify(s));corrupt.results=null;assert.equal(parseWorld(JSON.stringify(corrupt)).active,false)});
test('Finite Daily completion changes persistent world once; no missed-day reset, no incomplete reward',()=>{let s=open('bridge');s.daily=true;s.dailyDate='2026-10-4';s.sessionId='daily';s.slots=[new WorldSlot()];s.sessionRemaining=900;for(let i=0;i<3;i++)s=act(s,'place',i);s=E.next(s,at);assert.equal(s.phase,'ending');assert.equal(s.decorations,1);s=E.next(s,at);assert.equal(s.decorations,1);assert.equal(parseWorld(JSON.stringify(s)).days[0],'2026-10-4')});
test('Personalization requires three observed results, positive explicit feedback and preserves category allocations',()=>{const {recommendedWorld}=box.exports;const rows=[];for(let i=0;i<3;i++){let s=open('memory');s=E.tick(s,at+3000);for(const v of s.sequence)s=act(s,'panel',v);s.feedback='liked';s=E.next(s,at);s.results[0].id+='-'+i;rows.push(s.results[0]);}assert.equal(recommendedWorld(rows.slice(0,2),at),'bridge');assert.equal(recommendedWorld(rows,at),'memory');assert.equal(recommendedWorld(rows,at+8*86400000),'bridge')});
test('Tablet story splits learning into diverse short missions without changing category minutes or video cap',()=>{const {worldSlots}=box.exports;const source=[['LEARN',5,'INTERACTIVE'],['MOVE',5,'INTERACTIVE'],['CREATE',5,'GUIDED_OFFSCREEN'],['CALM',5,'VIDEO'],['LEARN',4,'VIDEO'],['MOVE',1,'INTERACTIVE'],['CREATE',3,'GUIDED_OFFSCREEN'],['CALM',2,'GUIDED_OFFSCREEN']].map(([category,minutes,mode])=>({category,minutes,mode,gameType:''}));const slots=worldSlots(source,'rocket');assert.equal(slots.length,9);assert.equal(slots.reduce((n,s)=>n+s.minutes,0),30);assert.equal(slots.filter(s=>s.mode==='VIDEO').reduce((n,s)=>n+s.minutes,0),9);assert.equal(slots[0].gameType,'rocket');assert.equal(slots[1].gameType,'memory');for(const c of ['MOVE','LEARN','CREATE','CALM'])assert.equal(slots.filter(s=>s.category===c).reduce((n,s)=>n+s.minutes,0),source.filter(s=>s.category===c).reduce((n,s)=>n+s.minutes,0));assert.equal(source[0].minutes,5)});
test('Foreground maximum window expires by elapsed time; pause/resume excludes the paused interval',()=>{let s=new WorldState();const c=new WorldCommand();c.id='budget';c.type='START_SESSION';c.minutes=15;c.slots=[new WorldSlot()];s=E.command(s,c,at);s=E.tick(s,at+60000);assert.equal(s.sessionRemaining,840);c.id='pause-budget';c.type='PAUSE_SESSION';s=E.command(s,c,at+60000);s=E.tick(s,at+600000);assert.equal(s.sessionRemaining,840);c.id='resume-budget';c.type='RESUME_SESSION';s=E.command(s,c,at+600000);s=E.tick(s,at+1440000);assert.equal(s.sessionRemaining,0);assert.equal(s.phase,'ending');assert.equal(s.results[0].skipped,true)});
test('Starting a replacement session records unfinished prior mission once instead of discarding its outcome',()=>{let s=open('bridge');s=act(s,'place',0);const c=new WorldCommand();c.id='replacement';c.type='START_SESSION';c.minutes=15;c.slots=[new WorldSlot()];s=E.command(s,c,at+10000);assert.equal(s.results.length,1);assert.equal(s.results[0].skipped,true);s=E.command(s,c,at+11000);assert.equal(s.results.length,1);s=open('bridge');for(let i=0;i<3;i++)s=act(s,'place',i);c.id='end-after-success';c.type='END_SESSION';s=E.command(s,c,at);assert.equal(s.results[0].completed,true)});
test('Back to World preserves completed session, reward and records across repeated taps, ticking and restart',()=>{let s=open('bridge');s.daily=true;s.dailyDate='2026-10-4';s.sessionId='return-home';s.slots=[new WorldSlot()];s.sessionRemaining=900;for(let i=0;i<3;i++)s=act(s,'place',i);s=E.next(s,at);const saved=JSON.stringify({results:s.results,events:s.events,days:s.days,decorations:s.decorations,slots:s.slots});s=E.backToWorld(s);assert.equal(s.phase,'hub');assert.equal(s.game,'');assert.equal(s.ended,true);assert.equal(E.status(s).completed,1);assert.equal(E.status(s).total,1);s=E.backToWorld(s);s=E.next(s,at);s=E.tick(parseWorld(JSON.stringify(s)),at+600000);s=act(s,'flower',1);assert.equal(s.phase,'hub');assert.equal(s.sessionId,'return-home');assert.equal(JSON.stringify({results:s.results,events:s.events,days:s.days,decorations:s.decorations,slots:s.slots}),saved);assert.equal(E.status(s).ended,true)});
test('Back to World cannot end an active mission or award an incomplete session',()=>{let s=open('bridge');assert.equal(E.backToWorld(s).phase,s.phase);const c=new WorldCommand();c.id='end-for-home';c.type='END_SESSION';s=E.command(s,c,at);s=E.backToWorld(s);assert.equal(s.phase,'hub');assert.equal(s.results.length,1);assert.equal(s.results[0].skipped,true);assert.equal(s.decorations,0);assert.equal(E.status(s).completed,0)});
test('Tablet and Phone RESUME_SESSION share safe memory transition and exclude paused time',()=>{for(const phase of ['preview','input']){let s=open('memory');s.sessionId='resume-memory';s.sessionRemaining=900;if(phase==='input'){s=E.tick(s,at+3000);s=act(s,'panel',s.sequence[0],at+3000)}const progress=s.progress;const retries=s.retries;const count=s.results.length;const pause=new WorldCommand();pause.id='phone-pause';pause.type='PAUSE_SESSION';s=E.command(s,pause,at+3000);const remaining=s.sessionRemaining;const elapsed=s.elapsed;s=E.tick(s,at+600000);assert.equal(s.sessionRemaining,remaining);assert.equal(s.elapsed,elapsed);const resume=new WorldCommand();resume.id='tablet-resume';resume.type='RESUME_SESSION';s=E.command(s,resume,at+600000);assert.equal(s.paused,false);assert.equal(s.progress,progress);assert.equal(s.retries,retries);assert.equal(s.results.length,count);assert.equal(s.lastTick,at+600000);if(phase==='preview'){assert.equal(s.previewAt,at+600000);assert.equal(s.flash,s.sequence[0])}else{assert.equal(s.phase,'input')}const replay=E.command(s,resume,at+600001);assert.equal(replay.lastTick,s.lastTick);s=E.tick(s,at+601000);assert.equal(s.sessionRemaining,remaining-1);assert.equal(s.elapsed,elapsed+1)}});
test('Cloud story requires video then three armed waypoints; gentle misses have no retry/attempt score and completion deduplicates',()=>{let s=open('watch');s=act(s,'done');assert.equal(s.phase,'watch');s=act(s,'story-step',0);assert.equal(s.progress,0);s=act(s,'video-ended');assert.equal(s.phase,'input');const videos=s.events.filter(e=>e.type==='VIDEO_COMPLETED').length;s=act(s,'video-ended');assert.equal(s.events.filter(e=>e.type==='VIDEO_COMPLETED').length,videos);s=act(s,'story-select');s=act(s,'story-step',2);assert.equal(s.phase,'input');assert.equal(s.progress,0);assert.equal(s.retries,0);assert.equal(s.attempts,0);for(let i=0;i<3;i++){s=act(s,'story-select');s=act(s,'story-step',i)}assert.equal(s.phase,'success');assert.equal(s.message,'The cloud found its home!');s=E.next(s,at);assert.equal(s.phase,'hub');assert.equal(s.results.length,1);assert.equal(s.results[0].style,'WATCHING');assert.equal(s.results[0].completed,true);s=E.next(s,at);assert.equal(s.results.length,1)});
test('Cloud story skip during video/interaction is not completed; reload/pause keeps path progress without replaying video',()=>{for(const phase of ['watch','input']){let s=open('watch');if(phase==='input')s=act(s,'video-ended');s=act(s,'skip');s=E.next(s,at);assert.equal(s.results.length,1);assert.equal(s.results[0].skipped,true)}let s=open('watch');s=act(s,'video-ended');s=act(s,'story-select');s=act(s,'story-step',0);s=parseWorld(JSON.stringify(s));assert.equal(s.phase,'input');assert.equal(s.progress,1);const c=new WorldCommand();c.id='pause-cloud';c.type='PAUSE_SESSION';s=E.command(s,c,at);assert.equal(act(s,'story-step',1).progress,1);c.id='resume-cloud';c.type='RESUME_SESSION';s=E.command(s,c,at+100000);assert.equal(s.phase,'input');assert.equal(s.progress,1)});
test('Video end during pause is retained without unpausing or replaying video',()=>{let s=open('watch');const c=new WorldCommand();c.id='pause-video-end';c.type='PAUSE_SESSION';s=E.command(s,c,at);s=act(s,'video-ended');assert.equal(s.paused,true);assert.equal(s.phase,'input');assert.equal(s.results.length,0);c.id='resume-video-end';c.type='RESUME_SESSION';s=E.command(s,c,at+60000);assert.equal(s.phase,'input');assert.equal(s.paused,false)});
test('Story return advances an existing Daily slot once, without automatic continuation before return',()=>{let s=open('watch');s.sessionId='story-flow';s.sessionRemaining=900;const story=new WorldSlot();story.category='CALM';story.mode='VIDEO';const next=new WorldSlot();next.gameType='memory';s.slots=[story,next];s=act(s,'video-ended');for(let i=0;i<3;i++){s=act(s,'story-select');s=act(s,'story-step',i)}assert.equal(s.slotIndex,0);assert.equal(s.results.length,0);s=E.next(s,at);assert.equal(s.slotIndex,1);assert.equal(s.game,'memory');assert.equal(s.results.length,1);assert.equal(s.results[0].completed,true);s=E.next(s,at);assert.equal(s.results.length,1);assert.equal(s.slotIndex,1)});
console.log(`${passed} Tablet world rule checks passed; native gestures/animations require emulator verification.`);
